#! /bin/sh

# gap defined in configuration.nix
# top padding enforced by panel
export PANEL_HEIGHT=0 # 25

query() {
    xrdb -query -all | awk -F "[ \t]+" "/$1:/"'{print $2}'
}

##################################################
# Settings
# --------

# Window Gap/Padding Settings
bspc config window_gap $gap
bspc config top_padding $PANEL_HEIGHT
bspc config left_padding 0
bspc config right_padding 0
bspc config bottom_padding 0

# Various Settings
bspc config gapless_monocle true
bspc config borderless_monocle true
bspc config single_monocle true
bspc config paddingless_monocle false

# Color Settings
bspc config focused_border_color "$(query bspwm.border.focused)"
bspc config normal_border_color "$(query bspwm.border.normal)"
bspc config presel_feedback_color "$(query bspwm.presel.color)"
bspc config border_width 2

# Behavior Settings
bspc config focus_follows_pointer true
bspc config pointer_follows_focus true

# Settings for Manual Splitting
bspc config split_ratio         0.50

# Create and Name 10 Desktops
bspc monitor -d I II III IV V VI VII VIII IX X

##################################################
# Autostart apps
# --------------

##  Autogap adjusts windowgap automatically according to the number of
##  windows on the desktop. Using it disables negative window gap.
#betterAutogap &

# Reset layout back to tiled after all windows have been closed on a desktop
#resetMonocleOnCloseAll &

# Pseudo automatic mode: always splits focused window when opening new window
bspc config external_rules_command ~/.config/bspwm/pseudo_automatic_mode

# fix fonts if broken
[ "$(fc-list | grep -i terminus)" = "" ] && fc-cache -rv

# launch top bar
polybar -r -c ~/.config/polybar top &

# set desktop background
sh ~/.fehbg &
