#!/bin/sh

bspc monitor eDP-1 -d I II III IV V VI VII VIII IX X


bspc config split_ratio 0.5

bspc config window_gap 6
bspc config border_width 2

bspc config focused_border_color '#817f7f'
bspc config normal_border_color '#30302f'

bspc config focus_follows_pointer true
bspc config pointer_follows_focus true

bspc config borderless_monocle true
bspc config gapless_monocle true
bspc config single_monocle true


bspc rule -a "screenshot_util feh" state='floating'
bspc rule -a Zathura state='tiled'

# java gui fixes
export _JAVA_AWT_WM_NONREPARENTING=1
bspc rule -a sun-awt-X11-XDialogPeer state=floating

SXHKD_SHELL=/bin/sh sxhkd &

sh $HOME/.fehbg
setxkbmap -option caps:escape

pgrep polybar > /dev/null || polybar -r top &
libinput-gestures -v > /tmp/libinput-gestures-log.txt & #TODO: sometimes crashes
pgrep xbanish > /dev/null || xbanish &
picom &

#redshift -l 48:-122 &

