[helpers]

[default]
depends = []

[default.files]
"config/bspwm/bspwmrc" = "~/.config/bspwm/bspwmrc"
"config/sxhkd/sxhkdrc" = "~/.config/sxhkd/sxhkdrc"
"config/polybar/config.ini" = "~/.config/polybar/config.ini"
"config/fd/ignore" = "~/.config/fd/ignore"
"config/alacritty.yml" = "~/.config/alacritty/alacritty.yml"
"config/rofi/config.rasi" = "~/.config/rofi/config.rasi"
"config/libinput-gestures.conf" = "~/.config/libinput-gestures.conf"
"config/dunstrc" = "~/.config/dunst/dunstrc"
"config/picom.conf" = "~/.config/picom.conf"

"bin/screenshot_util.sh" = "~/.local/bin/screenshot_util.sh"
"bin/open_terminal_here.sh" = "~/.local/bin/open_terminal_here.sh"
"bin/bspwm_command_palette.sh" = "~/.local/bin/bspwm_command_palette.sh"
"bin/fit_aspect.sh" = "~/.local/bin/fit_aspect.sh"

[default.variables]
